# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation.

name: self-hosted workflow

on:
  pull_request:
    branches:
      - iostest
  push:
    branches:
      - iostest
jobs:
    
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.86.111.250:8080/"
        user: "ajeesh"
        token: ${{ secrets.JENKINS_PAT }}
        job: "iosmcn"
