# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

name: self-hosted workflow

on:
  pull_request:
    branches:
      - iostest
  push:
    branches:
      - iostest
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit tests
        run: go test ./...
        
  
  trigger_jenkins:
    runs-on: self-hosted  # This job runs on the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger Jenkins job
        run: |
          JENKINS_URL=http://54.86.111.250:8080/  # Replace with your Jenkins server URL
          JENKINS_JOB_NAME=iosmcn  # Replace with your Jenkins job name
          JENKINS_API_TOKEN=secrets.JENKINS  # Replace with your API token (store securely using secrets)

          curl -X POST -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/job/$JENKINS_JOB_NAME/build"
